### ISSUE TITLE
Need to update chatgpt-api it reads *Switch back to text-davinci-003 after OpenAI disabled the previous model *

### ISSUE THREAD

**Issue by aleksandr-vin** [timkmecl/chatgpt-vscode#10]
Otherwise extension is not working right now

**Comment by aleksandr-vin** [comment]
See https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.2.0

**Comment by timkmecl** [comment]
Hi Aleksandr, this is indeed what should be done to make it work again and is a simple fix anyone building from source can do. However I decided not to do it myself because using text-davinci-003 would costs users their OpenAI credits when using the extension, whereas it was free before, so if they update the extension without reading the new info they would be spending money without knowing (there is also already a version of this extension that uses other OpenAI models - [CodeGPT](https://github.com/timkmecl/codegpt)). I am now waiting for some new method of connecting to ChatGPT, and will update this project then. Thank you anyway, I am leaving this issue open so others that want to do this for their personal use will see.

**Comment by timkmecl** [comment]
The extension now uses the official API released this week, so this is now fixed.
