### ISSUE TITLE
 Slow Response and Timeout Error when using ChatGPT in Visual Studio Code

### ISSUE THREAD

**Issue by devxi** [timkmecl/chatgpt-vscode#12]
Dear Author,

I hope this message finds you well. I have been using your ChatGPT extension for Visual Studio Code for the past few days, and initially, it was working great with fast responses. However, suddenly the extension started to respond very slowly, and eventually, I received a timeout error.

I have checked my network connection and I am confident that it is not an issue with my network. I have also compared my experience with the official ChatGPT web page, and it is working perfectly fine.

Upon reviewing the Visual Studio Code developer logs, I found the following error message: "ChatGPT error 404" and "TimeoutError: ChatGPT timed out waiting for response".

I would greatly appreciate it if you could help me resolve this issue. Let me know if there is any additional information that I can provide to assist with troubleshooting.

Thank you for your time and effort in creating this extension.

Best regards,
nothing

**Comment by timkmecl** [comment]
Hi @devxi, unfortunately OpenAI disabled the model that was used in the backend, so the extension doesn't work at the moment - there is nothing wrong at your end. Currently, the only options for making it work would be either using GPT3 instead of ChatGPT which could cost users money (and you can already do this using my other extension [CodeGPT](https://github.com/timkmecl/codegpt)), or potentialy using a reverse proxy someone has set up for connecting to ChatGPT, but that would mean exposing users' API keys to an untrusted third party which could be a security risk. 

I am planning on updating the extension as soon as there is another, hopefully official method to connect to ChatGPT. My apologies for the current situation.

**Comment by timkmecl** [comment]
The extension now uses the official API released this week, so this is now fixed.
