### ISSUE TITLE
[ERROR] Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden

### ISSUE THREAD

**Issue by 9amcoder** [timkmecl/chatgpt-vscode#4]
After copy and paste the Clearance Token, Session Token and User Agent.
I got 403 error.

<img width="347" alt="Screenshot 2022-12-13 at 12 47 02 PM" src="https://user-images.githubusercontent.com/59545545/207407050-e7ef73c9-100b-4fb4-bc4a-ec5c3c05243f.png">

**Comment by timkmecl** [comment]
This is currently an issue for some users (see [this discussion](https://github.com/mpociot/chatgpt-vscode/issues/15) for more) caused by some for now unidentified problem in the way chatgpt-api communicates with server that will hopefully soon be solved. Therefore if you exactly followed the instructions from `README`, there is unfortunately nothing I can do for now, I will notify you once the solution is found and implemented.

For now, could you please tell me the operating system, browser and exact `user-agent` you are using? This may help us find something.

If anyone knows what is going on (here and in the thread linked), please let me know and I will fix it ASAP.

**Comment by delicacyyy** [comment]
> This is currently an issue for some users (see [this discussion](https://github.com/mpociot/chatgpt-vscode/issues/15) for more) caused by some for now unidentified problem in the way chatgpt-api communicates with server that will hopefully soon be solved. Therefore if you exactly followed the instructions from `README`, there is unfortunately nothing I can do for now, I will notify you once the solution is found and implemented.
> 
> For now, could you please tell me the operating system, browser and exact `user-agent` you are using? This may help us find something.
> 
> If anyone knows what is going on (here and in the thread linked), please let me know and I will fix it ASAP.

Please tell me how to get `vsix` file after `yarn package`

**Comment by timkmecl** [comment]
*I will paste my answer [from the original repo](https://github.com/mpociot/chatgpt-vscode/issues/15#issuecomment-1350556810) here which shows some new info:*

It looks like this problem is not limited to this project, but also to some other ones using chatgpt-api, probably caused by agressive CloudFlare protection. In my own testing, even when I tried to login to my account in Chrome right after using it inside Edge, I got a 403 error *inside the web version*. After I waited for several minutes and tried again, it disappeard, but this shows that the problem is not just with the javascript API.

The browser that you use for getting the tokens might influence the chance to get 403, especially chrome, so maybe try from another one (https://github.com/transitive-bullshit/chatgpt-api/issues/107#issuecomment-1349712906)

There might also be some account or IP flagging going on either by OpenAI or CloudFlare that increases the possibility of getting 403 especially if doing lots of requests often (https://github.com/transitive-bullshit/chatgpt-api/issues/96#issuecomment-1350275343)

I am currently working on upgrading the login method for the extension to include an option to login using email and password, which will hopefully help solve this, will update you all then. In the meantime, if anyone learns something new about this, feel free to post it here!

**Comment by eshack94** [comment]
Same issue here.

**Comment by ibiscp** [comment]
Same error using Firefox

**Comment by brzka** [comment]
Can confirm that the 403 error is coming up with Firefox.

**Comment by TimPickup** [comment]
Same using other browsers

**Comment by timkmecl** [comment]
Hi, thank you all for sharing the issue. It seems that OpenAI's Clodflare protection has become more agressive, so the extension may no longer work for some users (only return 403/429 errors). There is unfortunately nothing I can do for the moment, but I will update it when/if there is a solution.

**Comment by mohammad-oghli** [comment]
Check this thread from this [link](https://github.com/timkmecl/chatgpt-vscode/issues/6#issuecomment-1374584816) for the only workaround for the issue.

**Comment by timkmecl** [comment]
**This should now be solved in the latest version, download it from Marketplace**

New version uses a method described in [this tweet](https://twitter.com/GodlyIgnorance/status/1620270384150093825) (simple Node.js implementation [here](https://github.com/timkmecl/chatgpt-api-wrapper)), already implemented in the unofficial chatgpt api. Only the official API key from OpenAI needed.

**Comment by radiowave21** [comment]
Encountered the same issue with v1.1.10, using MS Edge.
