### ISSUE TITLE
Followed your Dec 14 instructions, still getting 403

### ISSUE THREAD

**Issue by alokc83** [timkmecl/chatgpt-vscode#6]
Is there anything that I am missing? 
I would appreciate the help. 
Thank you for reading and creating this extension.

Best, 
Alok C

**Comment by timkmecl** [comment]
Hi,
I am sorry to hear that. As I wrote in the other issue, if you followed all the instructions and still get the error, there is unfortunately nothing that can be done right now, since this is due to agressive CloudFlare protection (if you are using Chrome to get the tokens try some other browser). 
I hope this will be resolved by OpenAI or the creators of the unofficial API soon.

**Comment by Welding-Torch** [comment]
Hey @timkmecl will you be using the new `ChatGPTAPIBrowser` that should resolve a lot of people's 403 / 429 errors? Mentioned here https://github.com/transitive-bullshit/chatgpt-api/issues/111#issuecomment-1353848972 and you can also see the latest release here https://github.com/transitive-bullshit/chatgpt-api/releases (the v3.0.0 release)

Would be super cool if you did, I love using this extension ❤️

**Comment by abi** [comment]
@Welding-Torch unfortunately the v3.0.0 release only works on Node 18 (VSCode is on node 16 and cannot be changed). I've also had trouble getting Puppeteer which is used for browser automation there to play nice with Webpack in a VSCode extension.

**Comment by timkmecl** [comment]
Hey @Welding-Torch thank you for the compliments! I am planning on using the updated API as soon as possible, but I think it currently cannot be used inside a VSCode extension due to their use of Pupeteer and higher required node version (see https://github.com/transitive-bullshit/chatgpt-api/issues/137 for anyone interested). Therefore I am waiting for any potential fix or changes by the makers of the API. 

@abi did you by any chance manage to get something work with your extension?

**Comment by abi** [comment]
@timkmecl No, I can't get Puppeteer to be included with my extension :(

**Comment by alokc83** [comment]
Thank you all for participating. I really appreciate it.

**Comment by leon-up9** [comment]
I got 403 error too even after upgrading to node 18 :(

**Comment by mohammad-oghli** [comment]
It seem that 403 error is still in all ChatGPT extensions that are using unofficial API due to aggressive Cloudflare protection. The only workaround for this issue is what [gencay](https://github.com/gencay) introduced in his [extension](https://github.com/gencay/vscode-chatgpt#setup) which is Zero-Config Autologin lets the extension grab the required tokens automatically using puppeteer. I tested on my VS Code and it worked perfectly without any errors.

**Comment by timkmecl** [comment]
**This should now be solved in the latest version, download it from Marketplace**

New version uses a method described in [this tweet](https://twitter.com/GodlyIgnorance/status/1620270384150093825) (simple Node.js implementation [here](https://github.com/timkmecl/chatgpt-api-wrapper)), already implemented in the unofficial chatgpt api. Only the official API key from OpenAI needed. (@mohammad-oghli @abi )
